type GetToKnowRaw = {
  ID: number;
  email?: string;
  variant: string;
  name: string;
  q1?: string;
  q2?: string;
  q3?: string;
  image?: string;
  consent?: ("nettside" | "some")[];
};
  
const getToKnowResultsRaw: GetToKnowRaw[] = [
  {
    ID: 2,
    email: "ssb@variant.no",
    variant: "Simen Strøm Braaten",
    name: "Simen Strøm Braaten",
    q2: "10",
    q3: "Har vinni 10 Peppes-pizzaer, én tur til Harstad, én mobiltelefon, og noen småleiker i ulike basketkonkurranser. Er en generelt engasjert type, og liker veldig godt å høre om hva andre er engasjert i (både stort og smått). For min egen del varierer det fra måned til måned – fra å lære å spille piano og musikkteori, til ergonomiske tastaturer og pensjonsparing.",
    image: "/images/varianttur/bliKjent/Simen.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 3,
    email: "jek@variant.no",
    variant: "Jakob Endrestad Kielland",
    name: "Jakob Endrestad Kielland",
    q2: "6. 2 grønne, 3 svarte og 1 sølv.",
    q3: "Jeg er skikkelig interessert i dataspill, og har blitt veldig vininteressert det siste året. Jeg kan generelt bli interessert i det aller meste, og elsker å høre om sære ting andre er nerder for.",
    image: "/images/varianttur/bliKjent/Jakob.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 4,
    email: "ans@variant.no",
    variant: "Anders Njøs Slinde",
    name: "Anders NS",
    image: "/images/varianttur/bliKjent/Anders_NS.png",
    consent: ["nettside"],
  },
  {
    ID: 5,
    email: "cmnk@variant.no",
    variant: "Carina Marie Nordli Krøger",
    name: "Carina ",
    q1: "Designer ulike greier.",
    q2: "9 stykker! Husker ikke farge på alle, men en del var hvite",
    q3: "Jeg samler egentlig ikke aktivt på dette, men jeg har en del sjiraffer/ting med sjiraff på etterhvert. Folk pleier å telle dem når de er på besøk.\n\nJeg trodde jeg hatet å strikke helt til jeg begynte under pandemien. Og nå er jeg avhengig.\nMin favorittaktivitet er å gå på kafé <3",
    image: "/images/varianttur/bliKjent/Carina.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 6,
    email: "jb@variant.no",
    variant: "Jacob Berglund",
    name: "Jacob Berglund",
    q1: "Jag försöker göra Sparebank1s nettbank lite bättre varje dag. Mer specifikt allt som har med kredittkort att göra. ",
    q2: "8. Grön, dörrfärgad, vit, vit, vit, vit, off-vit och slutligen... vit.",
    q3: "Jag gillar att fiska. Helst i strömmande vatten där man kan plaska runt med vuxenstövlar (också känd som vadare). I musikväg så blir det gärna olika typer av metal, men det mesta går in :D",
    image: "/images/varianttur/bliKjent/Jacob.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 7,
    email: "ma@variant.no",
    variant: "Maciek Adamczyk",
    name: "Maciek Adamczyk",
    q1: "Jeg skriver kode, stort sett nettsider! Nå i det siste jobber med flere deler av NTE systemene.",
    q2: "8! 2 i Larvik og 6 i Trondheim. \n1:grønn, 2:hvit, 3:grå, 4:hvit, 5:hvit-ish, 6:hvit, 7:grønn, 8:hvit-ish",
    q3: "-Liker å campe ute i naturen, helst ved et vann hvor jeg kan fiske litt 🏕️\n-Har ridd på en ku når jeg var liten!\n-Bærer på flere skruer og en plate i høyre hånden (men piper ikke i sikkerhetskontrollen på flyplassen!)\n-Født og oppvokst i Polen, derav navnet\n-Liker å stå bak en dj-mixer\n-Kan spille gitar, trommer og litt piano\n\n\n",
    image: "/images/varianttur/bliKjent/Maciek.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 8,
    email: "mg@variant.no",
    variant: "Magnus Gule",
    name: "Magnus Gule",
    q1: "Lager middag som unga ikke liker",
    q2: "3. Grønn alle sammen.",
    q3: "Føler meg selvsikker med munnharpe",
    image: "/images/varianttur/bliKjent/Magnus_Gule.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 9,
    email: "sge@variant.no",
    variant: "Sigrid Greiff Elnan",
    name: "Sigrid Greiff Elnan",
    q1: "Jobb -> hjem -> lage middag -> sitter på sofaen med enten noe å se på, lesing eller video spill",
    q2: "5 postkasser, 1 hvit, 1 grønn og 3 grå",
    q3: "Fun fact: Har identisk postkasse-svar som Ida. \n\nEllers går hobbier i musikk, både å høre og å spille, bøker (fantasy/sci-fi), spill (video, brett og rolle) og alt for mye tid forran youtube eller strømmetjenester. ",
    image: "/images/varianttur/bliKjent/Sigrid.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 10,
    email: "ima@variant.no",
    variant: "Ida Marie Andreassen",
    name: "Ida Marie Andreassen",
    q1: "Først på jobb, før jeg drar hjem og spiser middag, etterfulgt av strikking eller Zelda",
    q2: "5 postkasser, 1 hvit, 1 grønn og 3 grå",
    q3: "Fun fact: har nøyaktig samme svar på postkasse-spørsmålet som Sigrid\n\nEllers, liker jeg å strikke, lese fantasy-bøker og spille Zelda. Spise goood mat. ",
    image: "/images/varianttur/bliKjent/Ida_Marie.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 11,
    email: "mlsk@variant.no",
    variant: "Mari Lise Stenvik Kvistad",
    name: "Mari Lise Stenvik Kvistad",
    q1: "Jobber, trener, strikker👵🏻",
    q2: "6: Grønn, grå, hvit",
    q3: "Har snart 1 plante per kvm jeg bor på, hører helst på rock/metal, og begynte å drikke kaffe som 7-åring",
    image: "/images/varianttur/bliKjent/Mari_Lise.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 12,
    email: "oms@variant.no",
    variant: "Odd Morten Sveås",
    name: "Odd Morten",
    q1: "Koker kaffe, venter på at Morten skal komme inn døra og ellers prøver å få dette selskapet til å bli litt bedre hver dag. ",
    q2: "Sikkert 7, de fleste grønne. Den jeg har nå, har jeg ikke nøkkel til. ",
    q3: "Jeg har vært trener for tidenes olympier.",
    image: "/images/varianttur/bliKjent/Odd Morten.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 13,
    email: "mt@variant.no",
    variant: "Mathias Tørhaug",
    name: "Mathias Tørhaug",
    q1: "Programmerer, styrketrening, Top Gear og dank",
    q2: "1 hvit 😇",
    q3: "Skulle delta i NM i luftballong, men det ble dårlig vær:(",
    image: "/images/varianttur/bliKjent/Mathias_T.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 14,
    email: "mt@variant.no",
    variant: "Mathias Tørhaug",
    name: "Fredrick Becker",
    q1: "Programmerer, styrketrening, film og dank",
    q2: "1 svart",
    q3: "Skulle også være med i NM i luftballong, men det ble dårlig vær:(",
    image: "/images/varianttur/bliKjent/Fredrick.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 15,
    email: "ss@variant.no",
    variant: "Sarah Serussi",
    name: "Sarah",
    q1: "Jobber, henter i barnehagen, spiser middag med familien, legger Sophia, ser på trash på TV og spiser popcorn",
    q2: "7-8. Alle var hvite bortsett fra en som var grønn",
    q3: "Jeg liker å strikke, hekle og fikse ting. Hiphop er min favorittmusikk, og jeg har blitt veldig glad i RockRap/RapRock/RackRop. Funfacts: Jeg likte ikke sjokolade før jeg fikk barn også snakker jeg hebraisk. Brenner for å få flere kvinner inn i teknologibransjen og synes det er gøy å lære bort koding til barn.",
    image: "/images/varianttur/bliKjent/Sarah.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 16,
    email: "ssm@variant.no",
    variant: "Stina Sofie Møller",
    name: "Stina Sofie Møller",
    q1: "Designer i Variant, jobber på prosjekt til Sikt.\n",
    q2: "3 - Hvit, Grønn (Tror jeg, fikk aldri post i den), Grå - nei måtte ned å sjekke, den er hvit/creme",
    q3: 'Guilty pleasure "Say Yes to the Dress" og dårlige julefilmer på Netflix\nVinteren er den beste årstiden!',
    image: "/images/varianttur/bliKjent/Stina_Sofie.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 17,
    email: "ssm@variant.no",
    variant: "Stina Sofie Møller",
    name: "Erlend Hansen",
    q1: "Eat, work (byggingeniør hos Multiconsult), sleep, repeat",
    q2: "Tenker du på postkasse som postmann frakter post i? Aldri hatt.",
    q3: "- Samler på tørre vitser\n- All type musikk. Liker godt rock/metall.\n- Beermile pers på 06:20",
    image: "/images/varianttur/bliKjent/Erlend.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 18,
    email: "sb@variant.no",
    variant: "Stine Bechmann",
    name: "Stine Bechmann",
    q1: "jobb - hjem - middag - legge unger - vaske klær - tv - sove",
    q2: "9 postkasser (7 adresser), Grønn, Tre med solnedgang, Grå, Hvit, Grønn, Grå, Grå, Grønn, Hvit\n",
    q3: "Kan anbefale podcasten Fantorangens vitseshow",
    image: "/images/varianttur/bliKjent/Stine.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 19,
    email: "hr@variant.no",
    variant: "Hilde Osmo Reindal",
    name: "Hilde Reindal",
    q1: "Går tur med hunden vår Oswald som er en pensjonist født i ung kropp. Vi har som regel en snittfart på 2 km/t. :snegleemoji:",
    q2: "Dette har vi snakket om Lotta-Linn. Jeg tror samtlige har vært standard grønn postkasse, utenom den jeg har nå som er gråhvit. ",
    q3: "Har vært medlem av en jenteklan i CS da jeg gikk på videregående. Snakker med meg selv når jeg sover. Liker ikke norges nasjonalrett: taco.",
    image: "/images/varianttur/bliKjent/Hilde_Peter.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 20,
    email: "th@variant.no",
    variant: "Tormod Haugene",
    name: "Tormod Haugene",
    q1: "Våkner av at 2-åringen synger tøffe-tøffe-toget og nasjonalsangen kl. 05:30. Pakking og styring med elsykkel til barnehage og jobb. Taste, prate og jobbe på. Henting, middag, aktivisering av 2-åring, legging. Egentid...",
    q2: "9! Grønn, hvit og grå",
    q3: "Suuperinteressert i bytegning og akvarellmaling! Kommer til å selge kaffetrakteren ganske snart - hva skal man med den når man brygger det bedre for hånd? Har 14 par ski, 4 sykler og løpesko med tær.",
    image: "/images/varianttur/bliKjent/Tormod.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 21,
    email: "mlsk@variant.no",
    variant: "Mari Lise Stenvik Kvistad",
    name: "Erlend Brenne Sivertsen",
    q1: "Jobber, trener, spiser, tester nye matoppskrifter",
    q2: "3-4 grønne og 1-2 hvite",
    q3: "Liker klatring og å kjøre MC, samler på støv, og hører helst på heavy musikk. Alltid på jakt etter å optimalisere pizzadeigoppskrifter",
    image: "/images/varianttur/bliKjent/Erlend (Følge- Mari Lise).png",
    consent: ["nettside", "some"],
  },
  {
    ID: 22,
    email: "th@variant.no",
    variant: "Tormod Haugene",
    name: "Daniél Indahl Aubert",
    q1: "Tar på meg sokkene. Baker en kake. Sykler på 3,5 minutter ned fra byåsen til St. Olavs hvor jeg arbeider som anestesilege. Redder noen liv, serverer kake - folk elsker det. Bruker 4 minutter - ikke at det spiller noen rolle - og gjør meg klar for kveldens ekstremsport eller sofachill. 🍰🚵🏻‍♀️",
    q2: "Denne vet jeg ikke, Daniél, men jeg kan nevne på at é-en er fransk! 🥖",
    q3: 'Samler på utstyr. Ikke så farlig hva, men det må være utstyr - "stash". Mye terrengsykling/enduro, klatring inne og ute. Har gått Amundsenløpet (over Hardangervidda på tvers) i 30 minus. Lager de villeste kakene.',
    consent: ["nettside", "some"],
  },
  {
    ID: 23,
    email: "lhd@variant.no",
    variant: "Linn Helen Dyrhaug",
    name: "Linn Helen Dyrhaug",
    q1: "Jobber, leker med Brio-tog, vasker grøt fra bord, gulv og vegger og prøver å få en hund til å gå fint i bånd. ",
    q2: "Har hatt 11 ulike leveringsadresser for nettshopping men ikke like mange fysiske postkasser.",
    q3: "Går og løper, på sti og mølle, med og uten baby og hund. Ønsker å padle mer i kano og kajakk, sove i telt og hengekøye og koke kaffe på primus, mer enn det jeg har gjort det siste halvannet året. Samler på bursdags- og julekort. Basic på musikkfronten og kan ingen partytriks - rimelig kjedelig på fest altså. ",
    image: "/images/varianttur/bliKjent/Linn_Helen.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 24,
    email: "jbb@variant.no",
    variant: "Jonas Brendryen Bjøralt",
    name: "Jonas Brendryen Bjøralt",
    q1: "Koder ting og drikker (forsøkt) modererte mengder kaffe. \n\nFør/etter jobb går dagen stort sett med til å passe/debugge barna mine på 6-ish uker og 3 år. \nMed andre ord går det mye i trilleturer, bleieskift, lego, vannkrig, gjemsel og sånne ting. ",
    q2: "11\n\nStort sett grønne. Noen røde og en hvit. ",
    q3: 'Hobbyer? Hhahahahahahah (Neida liker å dykke, sykle, fjellturer, friluftsliv, fiske og gaming (når jeg kan)) \n\nFun-facts: \n - Kronisk dialektforvirra \n - Veldig svak for tørr humor \n - Planlegger en "glutenfest" når St. Olavs legger ut en patch for glutenallergi',
    image: "/images/varianttur/bliKjent/Jonas_BB.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 25,
    email: "mck@variant.no",
    variant: "Malin C. Karlsen",
    name: "Malin C. Karlsen",
    q1: "Jobber, tar vare på unger, går kanskje en tur i Bymarka",
    q2: "Aner ikke! Men den vi har nå er hvit",
    q3: "Jeg samler på strikkeinspirasjon og uferdige strikkeprosjekter :innocent:",
    image: "/images/varianttur/bliKjent/Malin.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 26,
    email: "oms@variant.no",
    variant: "Odd Morten Sveås",
    name: "Rebekka",
    q1: "Leder en fantastisk gjeng som bygger neste generasjon Varianter. Og nyter en Pepsi Max",
    q2: "Seks stykker. Vil tro de fleste var mørk smaragd. ",
    q3: 'Jeg kan bøye knærne "feil" vei. Kan summen på alle mulige yatzy-kast utenatt. ',
    image: "/images/varianttur/bliKjent/Rebekka.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 27,
    email: "ae@variant.no",
    variant: "Astrid Eldhuset",
    name: "Astrid Eldhuset",
    q1: "Starter dagen med å spise kjøleskapsgrøt før jeg drar på jobb. Hvis det er mandag kan jeg kose meg på korøving om kvelden (hurra!). Ellers varierer det veldig hva dagen bringer. Sosialisering? Trening? Baking? Strikking? Sying? En god blanding er det beste :)",
    q2: "Hmm, det er et godt spørsmål. Jeg tror det er ca. ni. Fargen jeg har hatt lengst gjennom livet er mørkegrønn, men jeg har også vært borti hvit, rødbrun og grå.",
    q3: "Hobbiene mine inkluderer blant annet å synge i kor, håndarbeid, baking og turorientering. Jeg gjør et halvhjertet forsøk i å samle på souvenirskjeer fra steder jeg har vært, men jeg har helt mistet oversikten over hvilke skjeer jeg faktisk har. Av litt mer eksotiske fun facts kan jeg nevne at jeg har klappet et veldig kosete vortesvin i Sør-Afrika. I den forbindelse lærte jeg at Pumba i Løvenes Konge (spoiler alert!) biologisk sett er et jentevortesvin.",
    image: "/images/varianttur/bliKjent/Astrid.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 28,
    email: "mos@variant.no",
    variant: "Magnus Olderø Sæther",
    name: "Magnus Olderø Sæther",
    q1: "Filosoferer, kjefter på unger, sykler, luftes av en hund, rydder frenetisk, tenker på døden, finner kveldsmatlykke, sniker meg til alenetid der jeg kan (do, viktig ærend), hører podkasten Ukraine: The latest, og dagens nye plateslipp på Tidal.",
    q2: "Tre. Grønn, hvit og grå. Og mailpostkasser fra NGT, Broadpark, Bluezone, Telenor, NTNU, Fylkeskommunen, Powel og Variant. ",
    q3: "Snekrer og kobler, spiller instrumenter og tar dem opp, samler på lyder, ",
    image: "/images/varianttur/bliKjent/Magnus_OS.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 29,
    email: "falk@variant.no",
    variant: "Falk Leander Østerhagen",
    name: "Falk Leander Østerhagen",
    q1: "Drikker kaffe fra mumikopper om morgenen, drikker vann fra syltetøyglass om kvelden. Noen ganger drikker jeg tran rett fra flaska, og andre ganger drikker jeg brus fra vinglass. ",
    q2: "Jeg har vært stolt eier av 5 (?) postkasser opp i gjennom årene. Når det kommer til farge har vel de fleste vært relativt vanlige (kommunegrønn, støvete blå), men jeg husker egentlig bare de to nyligste. Hvem vet, kanskje vi hadde en i neongul når jeg var baby?",
    q3: "Musikk er nais. Jeg liker å høre på musikk og dra på konsert. Nylig fikk jeg sjansen til å delta på en viss festival på marinen, det var sweet! Jeg foretrekker hiphop, metal, electronica, citypop, drum and bass, punk, og selvsagt intelligent dance music. ",
    image: "/images/varianttur/bliKjent/Falk.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 30,
    email: "mb@variant.no",
    variant: "Mikael Brevik",
    name: "Mikael Brevik",
    q1: "Lager kaffe, står i bilkø samtidig som jeg drikker nevnt kaffe, jobber og kjører hjem.",
    q2: "Jeg personlig har hatt 3 postkasser, hvorav samtlige hvit.",
    q3: "Lidenskaplig hobbyist i korte sprinter, tidligere spenstig og utmerket navle-estimatør.",
    image: "/images/varianttur/bliKjent/Mikael.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 31,
    email: "mhh@variant.no",
    variant: "Mathilde Haukø Haugum",
    name: "Espen Marsfjell Smevik",
    q1: "Jobber i barnehage og bruker fritiden på å spille gitar, gå på tur i skogen med hundene, leke med datteren min, trene eller spille dataspill. ",
    q2: "Tror jeg har hatt rundt 6 postkasser, der alle bortsett fra den vi har nå har vært grønn.",
    q3: "Jeg spiller gitar i et rockeband og spilte denne sommeren på Midnattsrocken i Lakselv 🤘",
    image: "/images/varianttur/bliKjent/Espen_MS.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 32,
    email: "mhh@variant.no",
    variant: "Mathilde Haukø Haugum",
    name: "Mathilde Haukø Haugum",
    q1: "Det meste av tiden bruker jeg på jobben i Variant, der jeg jobber som utvikler. På fritiden leker jeg med datteren min og våre to hunder, spiller dataspill, jobber med hobbyprosjekt og går tur i fjell og mark. ",
    q2: "Jeg vokste opp med en hvit postkasse. Har hatt en del grønne postkasser i diverse leieboliger i Trondheim (5stk!), men nå har vi kommet tilbake til hvit postkasse 🤍",
    q3: "Jeg synes det er morsomt å smake på nye og ukjente matvarer, noe som har ført til at jeg blant annet har smakt på hjernen til en uer-fisk 🫣 ",
    image: "/images/varianttur/bliKjent/Mathilde.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 33,
    email: "mf@variant.no",
    variant: "Mathias Flått",
    name: "Mathias Flått",
    q1: "Prøver å sammenstille data om fiskegrupper, og legge unger.",
    q2: "7; Grønn, Grå og Svart",
    q3: "Dataspill, Brettspill, Klatring og Curling.\nJeg har en alt for stor samling av trange klær og uspilte spill på steam. \nBruker ikke å ha annen lyd i headsettet enn støykansellering når jeg jobber 😶\nKan et nesten partytriks, du kan spørre meg for en demonstrasjon.",
    image: "/images/varianttur/bliKjent/Mathias_F.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 34,
    email: "ewa@variant.no",
    variant: "Ellen Wagnild-Antonsen",
    name: "Ellen Wagnild-Antonsen",
    q1: "Jobber som designer i Variant",
    q2: "Fire stykker, sannsynligvis med helt basic postkassefarge på uten at jeg husker mer konkret.",
    q3: "Driver en startup på fritiden, har vært bleiemodell som barn, og setter pris på en god disco funk-låt med et glass champagne i hånda. ",
    image: "/images/varianttur/bliKjent/Ellen.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 35,
    email: "jbl@variant.no",
    variant: "Jonas Brunvoll Larsson",
    name: "Jonas Brunvoll Larsson",
    q1: "På en vanlig ukedag blir det mye serietitting på sofaen etter jobb. Hvis jeg er virkelig flink, klarer jeg å komme meg en tur ut på trening før sofaen blir alt for tung å reise seg opp av. ",
    q2: "Jeg har hatt to postkasser. En hvit, og en stålgrå en. ",
    q3: "Jeg står på snowboard og kan svømme butterfly. Jeg har ingen partytriks, men er en racer på kabal. ",
    image: "/images/varianttur/bliKjent/Jonas_BL.png",
    consent: ["some", "nettside"],
  },
  {
    ID: 36,
    email: "line@variant.no",
    variant: "Line Skjærvik",
    name: "Line Skjærvik",
    q1: "Partall: Henger med kjæresten, hører på musikk, møter vennene mine, gjør yoga og vil helst være utendørs på kveldstid. Oddetall: er mamma og gjør yoga og lengter etter å være ute på kveldstid. #DenLukta! ",
    q2: "Uendelig mange. Grønne alle sammen (men den fra barndomshjemmet malte jeg en bukt og seilbåt på. Ble dritstøgg. Sånn seriøst. Maleriet er der fortsatt.)",
    q3: "Hobby: Male, skrive dikt, synger hele tiden, hører på musikk, yoga, fotograferer(prøver), mat (laging og spising), og drømmer om å ha hage og å være gartner. Musikk: soul, rock, indie, jazz, blues. (Og særlig 70-tallet i hjertet). Samler på lys med øynene ved å se på lyskilden så den blir uskarp (gjort det hele livet).",
    image: "/images/varianttur/bliKjent/Line_Raymond.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 37,
    email: "ewa@variant.no",
    variant: "Ellen Wagnild-Antonsen",
    name: "Vegard Berg Garvik",
    q1: "Jobber som takstmann",
    q2: "Tre postkasser - alle på samme postnummer #lade4ever",
    q3: "Jobber stadig med å perfeksjonere pizzaen på lørdager hjemme, liker rødvin med litt punch i (som passer til pizzaen) og er svak for slapstick-humor.",
    image: "/images/varianttur/bliKjent/Vegard.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 38,
    email: "mf@variant.no",
    variant: "Mathias Flått",
    name: "Ragna Torås Halseth",
    q1: "Ingeniørgeolog hos Norconsult: prosjekterer tunneler, vegskjæringer, byggegroper i berg, vannkrafttunneler",
    q2: "6. Grønn, brun, svart",
    q3: "Hobbyer: volleyball, buldring, dyrke grønnsaker, bake brød, reperasjonssøm. Samler på ingenting - prøver å kvitte meg med mest mulig. Musikk: Liker den musikken jeg hørte på/oppdaget for 10 år siden, har ikke tid til å høre på noe nytt. Fun fact: Seriemester i eliteserien i volleyball.",
    image: "/images/varianttur/bliKjent/Ragna.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 39,
    email: "line@variant.no",
    variant: "Line Skjærvik",
    name: "Raymond Løkken",
    q1: "Er med kjæresten min, ser på fotball med guttungen min og hører på musikk. ",
    q2: "8 postkasser. Hvite og grønne.",
    q3: "Samler på vinyl. Står på snowboard. Maler. Hører masse på musikk. Er pappa. ",
    consent: ["nettside", "some"],
  },
  {
    ID: 40,
    email: "jb@variant.no",
    variant: "Jacob Berglund",
    name: "Kine Berglund",
    q1: "Jeg jobber på en ortopedisk sengepost på St. Olavs, det betyr at min hverdag i hovedsak handler om å få mennesker med diverse skader opp av senga på en mest mulig skånsom måte så de ikke pådrar seg lungebetennelse, trykksår eller andre komplikasjoner. \n\nPå hjemmebane er dagen som regel sentrert rundt to små bøllefrø ved navn Edel (4) og Olov (2). ",
    q2: "7. Overraskende mange har hatt en sånn kjip grå/beige farge. ",
    q3: "Min hobby er å skrive, for ei stund sida arva jeg en Olympia Sm3 skrivemaskin så jeg kan leike forfatterspire anno 1953.  Funfacts om meg: jeg har vært ombord i den originale Hogwarts Express, jeg har besteget Kilimanjaro og jeg har en mild til moderat koffeinavhengighet.",
    image: "/images/varianttur/bliKjent/Kine.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 41,
    email: "ah@variant.no",
    variant: "Anders Hammervold",
    name: "Anders",
    q1: "Går tur med hunden",
    q2: "19, den siste er grønn",
    q3: "Jeg lager en god Beuf bourguignon :)",
    image: "/images/varianttur/bliKjent/Anders_Hammervold.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 42,
    email: "ah@variant.no",
    variant: "Anders Hammervold",
    name: "Marthe Hammervold",
    q1: "Går tur med hunden.",
    q2: "9 grønne",
    q3: "Jeg elsker bruktbutikker, og syr klær av gamle stoffer.",
    image: "/images/varianttur/bliKjent/Marthe.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 43,
    email: "kqn@variant.no",
    variant: "Kristin Qvenild Nesset",
    name: "Kristin",
    q1: "Har en topp dag på jobb i Variant, såklart! Drar hjem på sykkel til unger og hunder som skal på tur, trening, spilling, svømming og dans. Rydder opp i oppvaskmaskina etter crazy racoons, og prøver å strikke, lese og gå på tur i Estenstadmarka.",
    q2: "Jeg kommer til 11, men kan ikke huske andre farger enn den tradisjonelle grønne postkassen.",
    q3: "Jeg samler på religiøse symboler og figurer.",
    image: "/images/varianttur/bliKjent/Kristin.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 44,
    email: "kqn@variant.no",
    variant: "Kristin Qvenild Nesset",
    name: "Øystein",
    q1: "Står opp litt etter Kristin og drar på jobb i Trondheimsolistene. Drar deretter på fotballtrening som 5. trener og avslutter dagen med en tur med hundene før jeg tenker litt.",
    q2: "5 postkasser, men jeg er dessverre fargeblind.",
    q3: "Har fått terningkast 1 i VG.",
    image: "/images/varianttur/bliKjent/Øystein.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 45,
    email: "jbl@variant.no",
    variant: "Jonas Brunvoll Larsson",
    name: "Anne Marie Mathisen",
    q1: "Etter jobb drar jeg ofte på trening før jeg drar hjem og ser på The Office med Jonas",
    q2: "4, grønn, grå og hvit tror jeg",
    q3: "Dessverre ikke, men har hørt at jeg er helt ok å henge med uansett da :-D",
    consent: ["nettside", "some"],
  },
  {
    ID: 46,
    email: "ae@variant.no",
    variant: "Astrid Eldhuset",
    name: "Dirk Reinhardt",
    q1: "Min typiske dag dreier seg om en kombinasjon av forskning i kybernetikk og utendørseventyr. Dette betyr at jeg enten er nedsenket i detaljene av tilbakekoblede sløyfer og styringsalgoritmer, eller at jeg utfordrer mine egne grenser i naturen.",
    q2: "Jeg har hatt 16 postkasser gjennom livet mitt, og selv om fargepaletten kanskje ikke ville vunnet noen priser for livlighet, har de stort sett variert fra nyanser av hvitt til svart, av og til pyntet med et hint av sølv.",
    q3: "Kommer det regn eller solskinn, kan du se meg sykle, jogge langs en naturskjønn sti, eller ta en svømmetur i en innsjø. For å toppe det hele, er det ingenting som en forfriskende Aufguss-økt i en badstu, etterfulgt av den tradisjonelle klasken med en bjørkekvist. Min imponerende samling av utendørsutstyr og sykler (ifølge Astrid) blir bare overgått av antallet kneoperasjoner jeg har hatt. Jeg har en forkjærlighet for elektronisk musikk, muligens fanget opp da jeg studerte i Berlin. Her er noen sanger jeg oppdaget nylig:\n\nhttps://open.spotify.com/track/1HEd12Ca0vURsoMsxoHHAA?si=d0101bae3d694e83\nhttps://open.spotify.com/track/6ry0z6yotxEiqsxoKHpYBO?si=ed4340baf51b42e9\nhttps://open.spotify.com/track/7n8sDrEcuMt0yezLDhIbnN?si=bfdc7327587a4f04",
    image: "/images/varianttur/bliKjent/Dirk.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 47,
    email: "ps@variant.no",
    variant: "Petter Suul",
    name: "Louise Suul",
    q1: "Jobber som hotellsjef på P-Hotels, og er endelig tilbake etter svangerskapspermisjon.",
    q2: "7 totalt, og er mest fornøyd med den sorte",
    q3: "Fan av Taylor Swift, og sykt deppa for at jeg ikke har fått tak i billetter til 2024-turneen.",
    image: "/images/varianttur/bliKjent/Louise.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 48,
    email: "ps@variant.no",
    variant: "Petter Suul",
    name: "Petter Suul",
    q1: 'Lager grafiske ting, og holder på med evighetsprosjektet "oppussing"',
    q2: "3stk - hvit, blå, og sort",
    q3: "Kan en halv reinlender på torader (trekkspill)",
    image: "/images/varianttur/bliKjent/Petter.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 49,
    email: "jek@variant.no",
    variant: "Jakob Endrestad Kielland",
    name: "Olga Verbitskaia",
    q1: "I work with revenue management in an italian hotel chain, and I write my master's thesis.",
    q2: "Strange question. But I think 5 - almost all grey, one green",
    q3: "I collect postcards from the places I've visited (but mostly they're getting stolen by some friends or relatives, so the collection grows slowly). Don't know if it's a fun fact but I speak 4 languages and am learning a 5th one. I can't ride a bicycle.",
    image: "/images/varianttur/bliKjent/Olga.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 50,
    email: "tv@variant.no",
    variant: "Tore Vestues",
    name: "Tore Vestues",
    image: "/images/varianttur/bliKjent/Tore_V.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 51,
    email: "tv@variant.no",
    variant: "Tore Vestues",
    name: "Anna Vestues",
    image: "/images/varianttur/bliKjent/Anna.png",
    consent: ["nettside"],
  },
  {
    ID: 52,
    email: "hr@variant.no",
    variant: "Hilde Osmo Reindal",
    name: "Peter Skjerstad",
    q1: "Ser på bruer, lager middag, drar ut i skogen og kaster tøypølser som Hilde sender hunden til å hente, setter en pizzadeig til to pizza  i kjøleskapet til dagen etter (311 gram Caputo nuvola super mel, 200 gram vann, 2 teskje caputo pizzagjær, litt under 1 teskje salt). Hører en podcast om fantasy premier league for å forberede transfers til neste game week. ",
    q2: "Vokste opp med en grønn postkasse. Så flyttet jeg på hybel hvor det også var grønn postkasse. Flyttet inn i leilighet med kompiser hvor det var hvit postkasse. Flyttet så i sokkelleilighet med grønn postkasse. Dro på folkehøgskole hvor man hentet post på kontor. Flyttet til Møllenberg med hvit postkasse. Bodde i Thomas Angells gate,  Munkegata og på Bakklandet som alle hadde grå postsorteringsskap. Flyttet til Holbergs gate med sort postkasse, og så til Lilleby med sort postsorteringsskap.\n\nAltså: 3x grønne postkasser,1x sort postkasse, 2x hvite postkasser, 1x post fra kontor, 3x grå postsorteringsskap og 1x sort postsorteringsskap. ",
    q3: "Mulig jeg husker 50 desimaler av eulertallet. Har en sølvmedalje i kata fra et karatestevne på Fauske i 1998 og tok førsteplass i 2v2-turneringen i Warcraft 3 på FauskeLAN i 2003. ",
    consent: ["nettside", "some"],
  },
  {
    ID: 53,
    email: "ss@variant.no",
    variant: "Sarah Serussi",
    name: "Anders",
    q1: "Leverer i barnehage, jobber med byggingeniør-ting, familietid, trening",
    q2: "6 postkasser. Grønn, hvit, sølvfarget",
    q3: "Hobbyer: musikkproduksjon, trening, klatring (veldig noob). Samler ikke på noe (bortsett fra musikkprod-plugins hehe). Liker ikke danseband, reggae eller techno",
    image: "/images/varianttur/bliKjent/Anders_A.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 54,
    email: "mb@variant.no",
    variant: "Mikael Brevik",
    name: "Lene Ugelstad",
    q1: "Får opp mann (samboer, he not put a ring on it) og barn. Drar på jobb, hente barn på bhg/skole. Hjem for å lage middag. Resten av kvelden går til husarbeid, eller sannheten: ligge rett ut i sofaen.",
    q2: "fire postkasser: grønn, svart, grå og hvit",
    q3: "fun fact: farget håret blå/svart 2mnd før konfirmasjonen fordi det hadde Tom Delonge i Blink 182 🤘🏻",
    image: "/images/varianttur/bliKjent/Lene_JU.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 55,
    email: "falk@variant.no",
    variant: "Falk Leander Østerhagen",
    name: "Dag Helge Østerhagen",
    q1: "Trener, jobber, spiller litt, leser litt, ser i veggen",
    q2: "Oj. 6? 5 grønne og en grå.",
    q3: '•\tHar lest i overmåte mye science fiction og fantasy-bøker\n•\tDet første spillet jeg spilte var Hunchback på Commodore 64\n•\tHar vært yoga instruktør. \n•\tMest lytta på Spotify de siste seks månedene er Yaeji\n•\tSyns antall timer "Screen time" på telefonen min er pinlig høyt',
    image: "/images/varianttur/bliKjent/Dag_Helge.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 56,
    email: "mikkel@variant.no",
    variant: "Mikkel Dan-Rognlie",
    name: "Mikkel Dan-Rognlie",
    q1: "På en vanlig ukedag etter endt arbeidsdag (ofte litt sent…. B-menneske), så er det ganske ofte trening. Men først litt kos med kattepusen vår, Cindy 😻 Squash har mye fokus, eller trening som bygger opp om squashformen (kondisjon som spinning samt styrke og tøying/YinYoga for å unngå skader). I fint vær på sommeren blir det kanskje også en stisykkeltur.",
    q2: "3. Jeg har hatt 13 postkasser, hvorav 4 i Norge og 9 i Danmark. Husker virkelig ikke fargene utover at den forrige var grønn og nåværende er hvit.",
    q3: "4. Har det med å kaste meg over diverse ting og gå all-in i. En del interesser er samlet opp over årene. Glad i stisykling og både langrenn og toppturer på randonee-ski. Foto og kamera var en intens interesse i en periode, og ellers kaffenerding (espresso, perfeksjonering av teknikk, latte art, kaffebrenning, håndbrygg). Squash er den mest intense interessen, og de siste årene har jeg jobbet mye med forbedring og teknikk, deltatt på turninger og camps med profesjonelle coacher, og deltok også i NM i mars 2023. I juni var jeg på en «Squash Retreat» i El Gouna i Egypt i en uke med Gregory Gaultier (tidligere verdensmester og nummer 1), og var publikum på profesjonell turnering hvor de beste i verden konkurrerte.",
    image: "/images/varianttur/bliKjent/Mikkel.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 57,
    email: "mikkel@variant.no",
    variant: "Mikkel Dan-Rognlie",
    name: "Unni Lundberg",
    q1: "På en vanlig ukedag er jeg som regel på jobb som sykepleier på akuttmottaket. Lander gjerne på sofaen når jeg kommer hjem før det blir middag, trening eller sosialt med venner. ",
    q2: "Oi, hatt en del postkasser, den mest spennende var nok på Hawaii der jeg studerte deler av sykepleien. ",
    q3: "På sommeren er jeg glad i stisykling og på vinteren blir det noen toppturer på splitboard. Møte venninner og være sosial står høyt i kurs hele året. Har akkurat tatt en master i klinisk sykepleie ved siden av jobb, så nå gleder jeg meg til mer fritid fremover. ",
    image: "/images/varianttur/bliKjent/Unni.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 58,
    email: "cmnk@variant.no",
    variant: "Carina Marie Nordli Krøger",
    name: "Sverre",
    q1: "Utvikler dronesoftware og buldrer",
    q2: "4 i ukjent farge ",
    q3: "Har drevet en taekwondoklubb. \nEllers prøver jeg å få grønnsaker til å gro i den mørke bakgården vår.\nPartytriks: kan ta beina inn i lotus uten å bruke henda også gå på knærne ",
    image: "/images/varianttur/bliKjent/Sverre.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 59,
    email: "mg@variant.no",
    variant: "Magnus Gule",
    name: "Therese Oterhals",
    q1: "Rydde, brette klær, trøste, smøre matpakke og legge unger.",
    q2: "Grønne postkasser, kanskje 5-7?\n",
    q3: "Hobbyer: ridning, foto, dans. Liker musikk som highasakite, tre små kinesere, Charlotte Audestad, queen, Abba,\n\n",
    image: "/images/varianttur/bliKjent/Therese.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 60,
    email: "cb@variant.no",
    variant: "Christian Brevik",
    name: "Christian Brevik",
    q1: "Typisk småbarnsforeldreliv tenker jeg! Har en som har nettopp begynt på skole og ei i barnehagen, og begge får/krever en del oppmerksomhet og kjærlighet fra middagstid til legging. Bandit fra Bluey på Disney+ er forbildet mitt her. Men ellers så har tiden gått med på oppussing, bygger utekjøkken for tiden!",
    q2: "Først barndomshjem, så bygde familien nytt hus, så studenthybel, deretter kjøpte jeg leilighet i Trondheim, leide leilighet i Oslo, ny leilighet i Oslo, så til sist hus på Tiller. Det blir vel 7, og lurer på om samtlige postkasser har vært hvite!",
    q3: "Hobby: Når det er rolig i huset liker jeg å bryte freden ved å enten spille gitar, tromme, eller høylytt synge barnesanger med ungene. Hvis jeg skal være aktiv går det mest i buldring. Og hvis jeg skal slappe av er det PC-gaming, brettspill eller Magic: The Gathering som gjelder.\nSamler på: Hobbyer tydeligvis. Og vinyl/LP-plater, begynner å få en god samling 🤓\nMusikk: Liker alle sjangre! Punk, disco, jazz, hip-hop, det hakke nåkka nåkka å si. Har nok hørt mest på Dina Ögon og Ola Kvernberg i det siste. ",
    image: "/images/varianttur/bliKjent/Christian_Lena.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 61,
    email: "thj@variant.no",
    variant: "Truls Henrik Jakobsen",
    name: "Truls Henrik Jakobsen",
    q1: "Matematikk, brettspill, og progging!",
    q2: "Jeg har hatt 5 postkasser. I rekkefølge var de grønn, svart, grønn, hvit, og grønn.",
    image: "/images/varianttur/bliKjent/Truls Henrik.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 63,
    email: "cb@variant.no",
    variant: "Christian Brevik",
    name: "Lena Jansen",
    q1: "Haster avgårde fra jobb til skole og barnehage med mest sannsynlig dårlig samvittighet, for i en idealverden skulle ungene vært hentet helst før kl. 15. Resten av kvelden har jeg rollen som enten fredsmegler eller Gordon Ramsay, alt etter humøret (mitt eller ungenes). Når stillheten endelig rår er jeg godt plantet i sofaen med strikketøyet.",
    q2: "Jeg har forflyttet meg fra Rognan, til Bodø, til Vadsø, til Trondheim, enda en plass i Trondheim før jeg så ble jeg lurt inn til Christian i Trondheim. Etter det fikk vi oss en postkasse i Oslo, enda en i Oslo og til slutt en på Tiller. En total på 9 stk. fordelt på noen grønne og noen hvite.",
    q3: "Hobbyer? Hvem har tid til hobbyer? Samler på strikkeoppskrifter og flere timer i døgnet (denne uten hell). Av musikk liker jeg det meste, bortsett fra noe av det sære Christian liker 😏",
    consent: ["nettside", "some"],
  },
  {
    ID: 64,
    email: "llvm@variant.no",
    variant: "Lotta-Linn Vestli Moen",
    name: "Lotta-Linn",
    q1: "Jobber, trener, spiser middag og kanskje noe hobbyrelatert",
    q2: "10, hvit, grønn, grå",
    q3: "Hobbyer: male, sy, lese bøker, brettspill, pusling\nFun fact: allergisk mot blåfarge, og har rakfisk som foretrukket siste måltid",
    image: "/images/varianttur/bliKjent/Lotta-Linn_Magnus.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 65,
    email: "llvm@variant.no",
    variant: "Lotta-Linn Vestli Moen",
    name: "Magnus (Smith)",
    q1: "Studerer siving, bygg og miljøteknikk, jobber som BPA og løper",
    q2: "4, grå, grønn",
    q3: "Hobbyer: løping, gaming, fotball\nFun fact: synes havregryn med eplejuice er godt",
    consent: ["nettside", "some"],
  },
  {
    ID: 66,
    email: "lhd@variant.no",
    variant: "Linn Helen Dyrhaug",
    name: "Mia Moen Grendal",
    q1: "På en vanlig ukedag er jeg ute på tur med hunden Noah, selger noe på finn og ser en god serie på kvelden.",
    q2: "Jeg har hatt 9 postkasser. Grønn, rød, blå.",
    q3: "Når det kommer til hobbyer er jeg en ivrig finn/eBay-entusiast. Opptatt av film og tv-serier, fornyelse av hjemmet, og være ute i friskluft. Hører på alt fra Johnny Cash til Taylor Swift. Elsker fest, skulle gjerne lært et partytriks. ",
    image: "/images/varianttur/bliKjent/Mia.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 67,
    email: "km@variant.no",
    variant: "Kjetil Møkkelgjerd",
    name: "Kjetil Møkkelgjerd",
    q1: "Jobber, spiser, drikker, ser fjernsyn, sover",
    q2: "5. 4 hvite og 1 grønn",
    q3: "Hører stort sett på metalcore og deathcore. Men også litt danseband.",
    image: "/images/varianttur/bliKjent/Kjetil_Eirun.png",
    consent: ["nettside", "some"],
  },
  {
    ID: 68,
    email: "km@variant.no",
    variant: "Kjetil Møkkelgjerd",
    name: "Eirun Ranheim",
    q1: "Jeg jobber med barn.",
    q2: "5 stk. 1 grønn, 1 svart, 2 grå og 1 hvit",
    q3: "Jeg samler på gin og ser vanligvis ikke med enn 10-30 minutter av en film om gangen.",
    consent: ["nettside", "some"],
  },
  {
    ID: 69,
    variant: "Dora Oline Eriksrud",
    name: "Dora Oline",
    q2: "10 stk (grønn, hvit, grå)",
    q3: "Hund, planter, organisering og økonomi. Lager en applikasjon for privatøkonomi på fritiden (om det er ønskelig med flere: er utdannet barfottrimmer, feiret ferdig master med å kjøpe smartstore-bokser for organisering)", 
    image: "/images/varianttur/bliKjent/Dora Oline.png",
  },
  {
    ID: 70,
    variant: "Lene Ludvigsen",
    name: "Lene Ludvigsen",
    q1: "Står opp, tar båten over fjorden til jobb, som akkurat nå involverer å lage designsystem for WTW (GØY!), drar hjem, spiser middag og ser dagsrevyen, og spiller et eller annet på brett eller skjerm. Akkurat nå mest Baldur’s Gate, Tears of the Kingdom, eller Frosthaven.",
    q2: "18 kom jeg fram til, og jeg går ut i fra at storparten var grønne, kanskje noen hvite, men det er ikke noe jeg har tenkt mye over gitt!",
    q3: "•\tHar 24 timer i Baldur’s gate 3 (per 24.08)\n•\tHar en stor svart katt\n•\tHar bodd 9 år i Australia\n•\tSer Dagsrevyen hver kveld\n•\tLærte megselv å strikke som et nyttårsforsett i 2019, nå er det garn overalt\n•\tÅ stå opp før 10 eller legge meg før midnatt føles helt unaturlig for meg\n•\tHar frø for sikkert 100 ulike grønnsakssorter",
    image: "/images/varianttur/bliKjent/Lene_L.png",
  },
  {
    ID: 71,
    variant: "Lene Ludvigsen",
    name: "Tom",
    q1: "Står opp, drikker to kopper kaffe, mater kattene, jobber med 3D-modellering, spiser middag, ser Dagsrevyen, og spiller et eller annet på brett eller skjerm. Akkurat nå mest Baldur’s Gate, Cyberpunk 2077, eller Frosthaven.",
    q2: "8, de fleste var vel grønne, en lysegrå og en svart.",
    q3: "•\tHar 58 timer i Baldur’s gate 3 (per 24.08)\n•\tHar en liten svart katt\n•\tJobbet som folkehøgskolelærer på samme sted som Kristin har feriehus\n•\tHar aldri sett (og nekter å se) Titanic\n•\tStarter hver eneste dag med to kopper kaffe\n•\tSer også Dagsrevyen hver kveld\n•\tGikk til next level nerd og begynte male miniatyrer i 2022",
    image: "/images/varianttur/bliKjent/Tom.png"
  },
  {
    ID: 72,
    variant: "Tonje Evanger",
    name: "Tonje",
    image: "/images/varianttur/bliKjent/Tonje.png"
  },
  {
    ID: 73,
    variant: "Tonje Evanger",
    name: "Tom Arne",
    image: "/images/varianttur/bliKjent/Tom Arne.png"
  },
  {
    ID: 74,
    variant: "Johannes Røsvik",
    name: "Johannes Røsvik",
    q1: "Jeg jobber hardt med å få en av de mange halvferdige prosjektene mine til å kvalifsere som en fullverdig hobby, slik at jeg har et enkelt svar på denne type spørsmål 🤔",
    q2: "Seks, hvis hylla jeg hadde på folkehøyskolen teller. 2 x Grønn og 3 x Hvit, mens hylla var i tre.",
    q3: "En av mine halvferdige prosjekter er en radiobenk fra 60-tallet som jeg prøver å få liv i 📻",
    image: "/images/varianttur/bliKjent/Johannes.png"
  },
  {
    ID: 75,
    variant: "Johannes Røsvik",
    name: "Runar Hillestad",
    q1: "Jobb, youtube, sjakk",
    q2: "9 - Hvit, grønn, rød, grå som jeg husker",
    q3: "Hobby: sjakk, sykkel og musikk.",
    image: "/images/varianttur/bliKjent/Runar.png"
  },
];

export type GetToKnow = {
  name: string;
  q1?: string;
  q2?: string;
  q3?: string; 
  image?: string;
};


export interface VariantPlusOneModel {
  variant: string;
  people: GetToKnow[];
};
  
let variants: string[] = []; 
let getToKnowResults: VariantPlusOneModel[] = [];
getToKnowResultsRaw.forEach((person) => {
  if (person.q1 || person.q2 || person.q3 || person.image) {
    const variant = person.variant;
    if (variants.includes(variant)) {
      const found = getToKnowResults.find(element => element.variant === variant);
      if (found) {
        const mappedPerson: GetToKnow = {
          name: person.name,
          q1: person.q1,
          q2: person.q2,
          q3: person.q3,
          image: person.image,
        };
        found.people.push(mappedPerson);
      }
    } else {
      variants.push(variant);
      getToKnowResults.push( { variant: variant, people: [person] });
    }
  }  
});

export { getToKnowResults };