name: Code Quality Checks

on:
  pull_request:
    branches: [main, v3]

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/code-quality.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier --check .

      - name: ESLint Check
        run: npx eslint .
